const projectMeta = {
  'emailart.html':        { title: 'Reply All',                    year: '2025 - now', tags: ['generative', 'newsletter', 'HTML'], desc: 'A newsletter in which every email is a unique generative artwork, made of HTML code generated by a Python script and sent unreviewed to subscribers. The project questions how digital art holds value when its medium is mundane, copyable, and easily discarded.' },
  'oefenstof.html':       { title: 'Oefenstof',                    year: '2025',       tags: ['embroidery', 'generative', 'textile'], desc: 'A series of machine embroideries generated by a custom algorithm that investigates the relationship between traditional cross-stitch samplers and classical computational patterns.' },
  'thread.html':          { title: 'Thread',                       year: '2025',       tags: ['Art Blocks', 'generative', 'textile'], desc: 'A long-form generative collection of 250 screen-responsive works released on Art Blocks, serving as the on-screen counterpart to the Oefenstof embroidery series.' },
  'synths.html':          { title: 'Synths',                       year: '2024',       tags: ['generative', 'print'], desc: 'A series of 5 limited edition fine art prints, developed and curated from two generative algorithms.' },
  '33million.html':       { title: '33 Million',                   year: '2024',       tags: ['generative', 'embroidery', 'NFT'], desc: 'A generative series in two forms: 122 digital works released on Verse, of which 33 were translated into embroidery works with an embroidery machine. The algorithm scatters and rearranges patterns typical of historical needlework samplers.' },
  'yesyesno.html':        { title: '{yes, yes, no, yes}',          year: '2024 - now', tags: ['generative', 'tattoo'], desc: 'A limited edition generative tattoo project in which collectors use a parametric system to generate and select a personalized glyph.' },
  'generations.html':     { title: 'Generations',                  year: '2023',       tags: ['generative', 'collaboration', 'NFT'], desc: 'A collaboration with the Gees Bend Quiltmakers resulting in 500 generative digital quilts and a selection of physical quilts made from those outputs. The algorithm translates the quiltmakers legacy of improvisation, chance, and material reuse into code.' },
  'AFWIPS.html':          { title: 'Art For Walls In Public Spaces', year: '2022',     tags: ['generative', 'NFT', 'public space'], desc: 'A long-form generative series of 144 animated NFTs, created as an visual ambient system for public spaces.' },
  'perpetual.html':       { title: 'Perpetual Oscillations',       year: '2022',       tags: ['generative', 'NFT', 'ambient'], desc: '100 screen-responsive generative NFTs, designed to run as ambient evolving visuals for any screen.' },
  'patchedparadise.html': { title: 'Patched Paradise',             year: '2023',       tags: ['generative', 'NFT', 'textile'], desc: 'A generative series of 100 NFTs treating code as a material and exploring the tension between computational structure and the intuitive, material logic of textile craft.' },
  'loom.html':            { title: 'Loom',                         year: '2021',       tags: ['Art Blocks', 'generative', 'textile'], desc: 'A long-form generative collection of 200 works released on Art Blocks. The algorithm emulates a four-shaft weaving loom, horizontal and vertical threads interlace according to a virtual punching card generated at the moment of transaction. ' },
};

const projects = [
  { image: 'images/oefenstof/installation_01.jpg', href: 'oefenstof.html' },
  { image: 'images/oefenstof/installation_02.jpg', href: 'oefenstof.html' },
  { image: 'images/oefenstof/installation_03.jpg', href: 'oefenstof.html' },
  { image: 'images/oefenstof/installation_04.jpg', href: 'oefenstof.html' },
  { image: 'images/oefenstof/installation_05.jpg', href: 'oefenstof.html' },
  { image: 'images/oefenstof/installation_06.jpg', href: 'oefenstof.html' },
  { image: 'images/oefenstof/installation_07.jpg', href: 'oefenstof.html' },
  { image: 'images/oefenstof/gif2.gif', href: 'oefenstof.html' },
  { image: 'images/oefenstof/gif1.gif', href: 'oefenstof.html' },
  { image: 'images/yesyesno/yesyesno6_.jpg', href: 'yesyesno.html' },
  { image: 'images/yesyesno/yesyesno7_.jpg', href: 'yesyesno.html' },
  { image: 'images/yesyesno/yesyesno1_.jpg', href: 'yesyesno.html' },
  { image: 'images/yesyesno/yesyesno5_.jpg', href: 'yesyesno.html' },
  { image: 'images/generations/06.jpeg', href: 'generations.html' },
  { image: 'images/generations/installation_01.jpg', href: 'generations.html' },
  { image: 'images/generations/installation_04.jpg', href: 'generations.html' },
  { image: 'images/generations/19.png', href: 'generations.html' },
  { image: 'images/generations/installation_6.jpg', href: 'generations.html' },
  { image: 'images/generations/21.png', href: 'generations.html' },
  { image: 'images/generations/17.png', href: 'generations.html' },
  { image: 'images/generations/18.png', href: 'generations.html' },
  { image: 'images/33million/TENDER_Untitoed-21.jpg', href: '33million.html' },
  { image: 'images/33million/TENDER_Untitoed-16.jpg', href: '33million.html' },
  { image: 'images/33million/TENDER_Untitoed-12.jpg', href: '33million.html' },
  { image: 'images/33million/7.jpg', href: '33million.html' },
  { image: 'images/33million/9.jpg', href: '33million.html' },
  { image: 'images/33million/10.jpg', href: '33million.html' },
  { image: 'images/33million/13.jpg', href: '33million.html' },
  { image: 'images/33million/17.jpg', href: '33million.html' },
  { image: 'images/loom/1.png', href: 'loom.html' },
  { image: 'images/loom/5.png', href: 'loom.html' },
  { image: 'images/loom/7.png', href: 'loom.html' },
  { image: 'images/loom/13.png', href: 'loom.html' },
  { image: 'images/loom/4.png', href: 'loom.html' },
  { image: 'images/loom/8.png', href: 'loom.html' },
  { image: 'images/loom/16.png', href: 'loom.html' },
  { image: 'images/loom/14.png', href: 'loom.html' },
  { image: 'images/emailart/email-09.png', href: 'emailart.html' },
  { image: 'images/emailart/email-10.png', href: 'emailart.html' },
  { image: 'images/emailart/email-11.png', href: 'emailart.html' },
  { image: 'images/emailart/email-12.png', href: 'emailart.html' },
  { image: 'images/emailart/email-05.png', href: 'emailart.html' },
  { image: 'images/emailart/email-06.png', href: 'emailart.html' },
  { image: 'images/emailart/email-07.png', href: 'emailart.html' },
  { image: 'images/emailart/email-08.png', href: 'emailart.html' },
  { image: 'images/thread/8.png', href: 'thread.html' },
  { image: 'images/thread/13.png', href: 'thread.html' },
  { image: 'images/thread/29.png', href: 'thread.html' },
  { image: 'images/thread/30.png', href: 'thread.html' },
  { image: 'images/thread/32.png', href: 'thread.html' },
  { image: 'images/thread/43.png', href: 'thread.html' },
  { image: 'images/thread/47.png', href: 'thread.html' },
  { image: 'images/thread/80.png', href: 'thread.html' },
  { image: 'images/synths/Synths-031.png', href: 'synths.html' },
  { image: 'images/synths/Synths-037.png', href: 'synths.html' },
  { image: 'images/synths/Synths-040.png', href: 'synths.html' },
  { image: 'images/afwips/1.png', href: 'AFWIPS.html' },
  { image: 'images/afwips/2.png', href: 'AFWIPS.html' },
  { image: 'images/afwips/3.png', href: 'AFWIPS.html' },
  { image: 'images/afwips/4.png', href: 'AFWIPS.html' },
  { image: 'images/afwips/nabo.jpg', href: 'AFWIPS.html' },
  { image: 'images/perpetual/012.jpeg', href: 'perpetual.html' },
  { image: 'images/perpetual/015.jpeg', href: 'perpetual.html' },
  { image: 'images/perpetual/018.jpeg', href: 'perpetual.html' },
  { image: 'images/perpetual/020.jpeg', href: 'perpetual.html' },
  { image: 'images/perpetual/036.jpeg', href: 'perpetual.html' },
  { image: 'images/perpetual/lente1.jpg', href: 'perpetual.html' },
  { image: 'images/perpetual/lente2.jpg', href: 'perpetual.html' },
  { image: 'images/structured/structure-11.jpg', href: 'perpetual.html' },
  { image: 'images/patched/1.png', href: 'patchedparadise.html' },
  { image: 'images/patched/2.png', href: 'patchedparadise.html' },
  { image: 'images/patched/3.png', href: 'patchedparadise.html' },
  { image: 'images/patched/4.png', href: 'patchedparadise.html' },
  { image: 'images/patched/5.png', href: 'patchedparadise.html' },
  { image: 'images/patched/6.png', href: 'patchedparadise.html' },
  { image: 'images/patched/7.png', href: 'patchedparadise.html' },
  { image: 'images/patched/8.png', href: 'patchedparadise.html' },
];

function shuffleArrayInPlace(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

function preloadImage(src) {
  return new Promise(resolve => {
    const img = new Image();
    img.onload = resolve;
    img.onerror = resolve;
    img.src = src;
  });
}

function showProject(item) {
  const linkEl  = document.getElementById('featured-link');
  const imgEl   = document.getElementById('featured-image');
  const titleEl = document.getElementById('card-title');
  const yearEl  = document.getElementById('card-year');
  const descEl  = document.getElementById('card-desc');

  if (!linkEl || !imgEl) return;

  const meta = projectMeta[item.href] || {};
  linkEl.href = item.href;
  imgEl.src   = item.image;
  if (titleEl) titleEl.textContent = meta.title || '';
  if (yearEl)  yearEl.textContent  = meta.year  || '';
  if (descEl)  descEl.textContent  = meta.desc  || '';
}

function revealCard(cardEl) {
  cardEl.style.transition = 'opacity 250ms ease, transform 250ms ease';
  cardEl.classList.remove('card-hidden');
  cardEl.addEventListener('transitionend', () => {
    cardEl.style.transition = '';
  }, { once: true });
}

function initRandomizer() {
  const button = document.getElementById('randomize-btn');
  const cardEl = document.getElementById('project-card');
  if (!button) return;

  let order = shuffleArrayInPlace(projects.slice());
  let currentItem = order[0];

  if (cardEl) {
    cardEl.classList.add('card-hidden');
    showProject(currentItem);
    preloadImage(currentItem.image).then(() => revealCard(cardEl));
  } else {
    showProject(currentItem);
  }

  button.addEventListener('click', () => {
    const newOrder = shuffleArrayInPlace(projects.slice());
    const idx = newOrder.indexOf(currentItem);
    if (idx !== -1) newOrder.splice(idx, 1);
    const nextItem = newOrder[0] || currentItem;

    if (!cardEl) {
      currentItem = nextItem;
      showProject(currentItem);
      return;
    }

    cardEl.classList.add('card-hidden');

    Promise.all([
      preloadImage(nextItem.image),
      new Promise(resolve => setTimeout(resolve, 260)),
    ]).then(() => {
      currentItem = nextItem;
      showProject(currentItem);
      revealCard(cardEl);
    });
  });
}

function initGridView() {
  const gridContainer = document.getElementById('projects-grid');
  if (!gridContainer) return;

  const uniqueProjects = [
    { image: 'images/structured/structure-06.png', href: 'emailart.html' },
    { image: 'images/structured/structure-02.jpg', href: 'oefenstof.html' },
    { image: 'images/structured/structure-07.png', href: 'thread.html' },
    { image: 'images/structured/structure-08.jpg', href: 'synths.html' },
    { image: 'images/structured/structure-03.jpg', href: 'yesyesno.html' },
    { image: 'images/structured/structure-04.png', href: '33million.html' },
    { image: 'images/structured/structure-09.jpg', href: 'generations.html' },
    { image: 'images/structured/structure-10.png', href: 'patchedparadise.html' },
    { image: 'images/structured/structure-12.jpg', href: 'AFWIPS.html' },
    { image: 'images/structured/structure-11.jpg', href: 'perpetual.html' },
    { image: 'images/structured/structure-05.png', href: 'loom.html' },
  ];

  const cards = uniqueProjects.map(project => {
    const meta = projectMeta[project.href] || {};

    const link = document.createElement('a');
    link.href = project.href;
    link.className = 'grid-card';
    link.setAttribute('aria-label', 'Open project');

    const imageBox = document.createElement('div');
    imageBox.className = 'card-image-box';

    const img = document.createElement('img');
    img.dataset.src = project.image;
    img.alt = meta.title || '';
    img.style.opacity = '0';
    img.style.width = '100%';
    img.style.height = '100%';
    img.style.objectFit = 'contain';
    img.style.display = 'block';

    imageBox.appendChild(img);

    const cardMeta = document.createElement('div');
    cardMeta.className = 'card-meta';

    const titleRow = document.createElement('div');
    titleRow.className = 'card-title-row';

    const title = document.createElement('span');
    title.className = 'card-title';
    title.textContent = meta.title || '';

    const year = document.createElement('span');
    year.className = 'card-year';
    year.textContent = meta.year || '';

    titleRow.appendChild(title);
    titleRow.appendChild(year);

    const rule = document.createElement('hr');
    rule.className = 'card-rule';

    const desc = document.createElement('p');
    desc.className = 'card-desc';
    desc.textContent = meta.desc || '';

    cardMeta.appendChild(titleRow);

    if (meta.tags && meta.tags.length) {
      const tagsEl = document.createElement('div');
      tagsEl.className = 'card-tags';
      meta.tags.forEach(tag => {
        const tagEl = document.createElement('span');
        tagEl.className = 'card-tag';
        tagEl.textContent = tag;
        tagsEl.appendChild(tagEl);
      });
      cardMeta.appendChild(tagsEl);
    }

    cardMeta.appendChild(rule);
    cardMeta.appendChild(desc);

    link.appendChild(imageBox);
    link.appendChild(cardMeta);

    return { link, img };
  });

  cards.forEach(({ link }) => gridContainer.appendChild(link));

  const imageObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const img = entry.target;
        if (img.dataset.src) {
          img.src = img.dataset.src;
          delete img.dataset.src;
          img.addEventListener('load', () => { img.style.opacity = '1'; }, { once: true });
          imageObserver.unobserve(img);
        }
      }
    });
  }, { rootMargin: '50px' });

  cards.forEach(({ img }) => imageObserver.observe(img));

  cards.slice(0, 4).forEach(({ img }) => {
    if (img.dataset.src) {
      img.src = img.dataset.src;
      delete img.dataset.src;
      img.addEventListener('load', () => { img.style.opacity = '1'; }, { once: true });
    }
  });
}

function initActiveNavItem() {
  const filename = window.location.pathname.split('/').pop() || '';
  document.querySelectorAll('.nav-link').forEach(link => link.classList.remove('active'));
  
  if (filename === 'more.html') {
    document.getElementById('nav-about')?.classList.add('active');
  } else if (filename === 'selected.html') {
    document.getElementById('nav-structure')?.classList.add('active');
  }
}

function toggleNavMenu() {
  const navMenu = document.getElementById('nav-menu');
  navMenu?.classList.toggle('open');
  document.body.classList.toggle('menu-open', navMenu?.classList.contains('open'));
  document.querySelector('.nav-toggle')?.classList.toggle('menu-open', navMenu?.classList.contains('open'));
}

function closeNavMenu() {
  document.getElementById('nav-menu')?.classList.remove('open');
  document.body.classList.remove('menu-open');
  document.querySelector('.nav-toggle')?.classList.remove('menu-open');
}

function initImageLazyLoading() {
  const images = document.querySelectorAll('.image-grid img, .single-image img');
  images.forEach(img => img.loading = 'lazy');
  
  const imageObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const img = entry.target;
        const handleLoad = () => {
          img.classList.add('loaded');
          img.style.opacity = '1';
        };
        if (img.complete && img.naturalHeight !== 0) {
          handleLoad();
        } else {
          img.addEventListener('load', handleLoad, { once: true });
        }
        imageObserver.unobserve(img);
      }
    });
  }, { rootMargin: '100px' });
  
  images.forEach(img => {
    img.style.opacity = '0';
    imageObserver.observe(img);
  });
  
  Array.from(images).slice(0, 4).forEach(img => {
    img.loading = 'eager';
    if (img.complete && img.naturalHeight !== 0) {
      img.classList.add('loaded');
      img.style.opacity = '1';
    } else {
      img.addEventListener('load', () => {
        img.classList.add('loaded');
        img.style.opacity = '1';
      }, { once: true });
    }
  });
}

function initNav() {
  const nav = document.createElement('nav');
  nav.className = 'top-nav';
  nav.innerHTML = `
    <a href="index.html" class="site-title">ANNA LUCIA</a>
    <button class="nav-toggle" onclick="toggleNavMenu()" aria-label="Toggle menu">
      <img src="icons/hamburger.svg" class="hamburger-icon" alt="Menu" />
      <img src="icons/cross.svg" class="cross-icon" alt="Close" />
    </button>
    <ul class="nav-menu" id="nav-menu">
      <li><a href="selected.html" id="nav-structure" class="nav-link" onclick="closeNavMenu();">Work</a></li>
      <li><a href="more.html" id="nav-about" class="nav-link" onclick="closeNavMenu();">About</a></li>
    </ul>
  `;
  document.body.prepend(nav);
}

function initImageClickToOpen() {
  const modal = document.createElement('div');
  modal.id = 'img-modal';
  modal.innerHTML = '<button id="img-modal-close" aria-label="Close">✕</button><img id="img-modal-img" alt="" />';
  document.body.appendChild(modal);

  const modalImg = modal.querySelector('#img-modal-img');

  function openModal(src) {
    modalImg.src = src;
    modal.classList.add('open');
    document.body.style.overflow = 'hidden';
  }

  function closeModal() {
    modal.classList.remove('open');
    document.body.style.overflow = '';
    modalImg.src = '';
  }

  modal.addEventListener('click', e => { if (e.target === modal) closeModal(); });
  modal.querySelector('#img-modal-close').addEventListener('click', closeModal);
  document.addEventListener('keydown', e => { if (e.key === 'Escape') closeModal(); });

  document.querySelectorAll('.image-grid img, .single-image img').forEach(img => {
    img.style.cursor = 'pointer';
    img.addEventListener('click', function() {
      const src = this.getAttribute('src');
      if (src) openModal(src);
    });
  });
}

document.addEventListener('DOMContentLoaded', () => {
  initNav();
  initRandomizer();
  initGridView();
  initActiveNavItem();
  initImageLazyLoading();
  initImageClickToOpen();
});
